name: telegrosik
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  carousel_slider: ^5.0.0
  file_picker: ^8.1.3
  flutter:
    sdk: flutter
  flutter_barcode_listener: ^0.1.4
  flutter_lock_task: ^0.0.2
  fluttertoast: ^8.2.8
  image_picker: ^1.1.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
